management.tracing.sampling.probability=1.0

debug=true

management.tracing.enabled=true
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


logging.include-application-name=true

logging.level.io.opentelemetry=DEBUG
logging.level.zipkin2=DEBUG
logging.level.io.zipkin=DEBUG
logging.level.brave=DEBUG


deneme="Denendi 2"
