spring.application.name=customer-service

server.port=8081

eureka.client.refresh.enable=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

resilience4j.circuitbreaker.instances.orderServiceCB.slowCallDurationThreshold=2000ms
resilience4j.circuitbreaker.instances.orderServiceCB.slowCallRateThreshold=50

resilience4j.circuitbreaker.instances.orderServiceCB.minimumNumberOfCalls=4

resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.retry.retryAspectOrder=2
resilience4j.retry.instances.orderServiceRetry.maxAttempts=3
resilience4j.retry.instances.orderServiceRetry.waitDuration=500ms
resilience4j.retry.instances.orderServiceRetry.retryExceptions[0]=java.lang.Exception
management.endpoints.web.exposure.include=health,info,circuitbreakers,refresh
management.endpoint.circuitbreakers.enabled=true


resilience4j.circuitbreaker.instances.orderServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.orderServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCB.waitDurationInOpenState=15s
resilience4j.circuitbreaker.instances.order-service.automaticTransitionFromOpenToHalfOpenEnabled=true
logging.level.io.github.resilience4j=DEBUG

jwt.secret=ThisIsASuperSecretKeyForJWTSigningChangeMe123!
jwt.expiration-ms=3600000

deneme="deneme degıstı"


